
name: rust_pr

on : [ pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:

  check:
    runs-on : ubuntu-latest
    outputs:
      shouldRun: ${{ steps.run.outputs.shouldRun }}
    steps :
      - name: List commits on the pull request
        run: |
          response=$(curl --request GET \
          --url 'https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/commits' \
          --header 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
          --header 'Accept: application/vnd.github.v3+json' \
          --header 'Content-Type: application/json')
          echo $response > response.json
      - name: Get latest commit
        id: message
        run: |
          length=$(jq 'length' response.json)
          index=$(($length - 1))
          latest_commit=$(jq --argjson index $index '.[$index]' response.json)
          latest_commit_message=$(echo "$latest_commit" | jq -r '.commit.message')
          echo "::set-output name=message::$latest_commit_message"
      - name : Exit with fail
        id: run
        # if: "!contains( steps.message.outputs.message, '[build]' ) && !startsWith( steps.message.outputs.message, 'Merge ' )"
        if: "startsWith( steps.message.outputs.message, 'Merge ' )"
        run: echo "::set-output name=shouldRun::false"

  build:
    needs: check
    if: ${{ needs.check.outputs.shouldRun != 'false' }}
    strategy :
      fail-fast : false
      matrix :
        os : [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install latest stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build
    - name: Run all tests
      run: cargo test
